### ISSUE TITLE
RuntimeError: input and target shapes do not match

### ISSUE THREAD

**Issue by lordbutters** [hli1221/densefuse-pytorch#3]
I used train2014 as the trainset, but I got an error as follows, I dont know how to fix this bug.
**_RuntimeError: input and target shapes do not match: input [1 x 256 x 256], target [4 x 1 x 256 x 256] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12_**
Can you tell me what should i do ?

**Comment by hli1221** [comment]
> I used train2014 as the trainset, but I got an error as follows, I dont know how to fix this bug.
> **_RuntimeError: input and target shapes do not match: input [1 x 256 x 256], target [4 x 1 x 256 x 256] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12_**
> Can you tell me what should i do ?

It will better to answer your question, if you point out where this error occurred.
Generally, you should make sure that input is a tensor, and its shape is [B*C*H*W] which is same as target.

**Comment by hli1221** [comment]
> I used train2014 as the trainset, but I got an error as follows, I dont know how to fix this bug.
> **_RuntimeError: input and target shapes do not match: input [1 x 256 x 256], target [4 x 1 x 256 x 256] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12_**
> Can you tell me what should i do ?

It will better to answer your question, if you point out where this error occurred.
Generally, you should make sure that input is a tensor, and its shape is [B*C*H*W] which is same as target.

**Comment by lordbutters** [comment]
> > I used train2014 as the trainset, but I got an error as follows, I dont know how to fix this bug.
> > **_RuntimeError: input and target shapes do not match: input [1 x 256 x 256], target [4 x 1 x 256 x 256] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12_**
> > Can you tell me what should i do ?
> 
> It will better to answer your question, if you point out where this error occurred.
> Generally, you should make sure that input is a tensor, and its shape is [B_C_H*W] which is same as target.

here is the whole information, i just run "**_train_densefuse.py_**", and got this error. and the trainset is train2014
**_Start training.....
Epoch 0.....
BATCH SIZE 4.
Train images number 40000.
Train images samples 10000.0.
Traceback (most recent call last):
  File "train_densefuse.py", line 189, in <module>
    main()
  File "train_densefuse.py", line 28, in main
    train(i, original_imgs_path)
  File "train_densefuse.py", line 91, in train
    pixel_loss_temp = mse_loss(output, x)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 421, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/nn/functional.py", line 1716, in mse_loss
    return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: input and target shapes do not match: input [1 x 256 x 256], target [4 x 1 x 256 x 256] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12_**

**Comment by hli1221** [comment]
@lordbutters 
Thank you very much for your report.
I have reviewed my codes and there is some mistake in 'line 102, net.py'.
Please download the most recent version of our codes.

**Comment by lordbutters** [comment]
> @lordbutters
> Thank you very much for your report.
> I have reviewed my codes and there is some mistake in 'line 102, net.py'.
> Please download the most recent version of our codes.

OK! Thank you for your attention！I will have a try. Happy weekend!

**Comment by lordbutters** [comment]
> @lordbutters
> Thank you very much for your report.
> I have reviewed my codes and there is some mistake in 'line 102, net.py'.
> Please download the most recent version of our codes.

I have tried three times. It seems like there still have some bug in this project. ```

Traceback (most recent call last):
  File "train_densefuse.py", line 189, in <module>
    main()
  File "train_densefuse.py", line 28, in main
    train(i, original_imgs_path)
  File "train_densefuse.py", line 128, in train
    torch.save(densefuse_model.state_dict(), save_model_path)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/serialization.py", line 132, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'models/1e2/Epoch_0_iters_1000_Fri_Feb_28_23_00_38_2020_1e2.model'
```

I am sorry for disturb you for so many times. Hope you can fix it or tell me where is my mistake.

**Comment by lordbutters** [comment]
> @lordbutters
> Thank you very much for your report.
> I have reviewed my codes and there is some mistake in 'line 102, net.py'.
> Please download the most recent version of our codes.

I have tried your new code , it seems that there still have some problem in this project.
Here is the mistake info

**_Traceback (most recent call last):
  File "train_densefuse.py", line 189, in <module>
    main()
  File "train_densefuse.py", line 28, in main
    train(i, original_imgs_path)
  File "train_densefuse.py", line 128, in train
    torch.save(densefuse_model.state_dict(), save_model_path)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/torch/serialization.py", line 132, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/maiyuki/Documents/densefuse-pytorch-master/models/1e2/Epoch_0_iters_1000_Fri_Feb_28_23_15_22_2020_1e2.model'_**

I am sorry for disturb you for some many times. Hope you fix this bug or tell me where is my mistake.

**Comment by hli1221** [comment]
@lordbutters 
I have updated "train_densefuse.py" and the model file. Please download the new version.

**Comment by lordbutters** [comment]
> @lordbutters
> I have updated "train_densefuse.py" and the model file. Please download the new version.

The **_train_densefuse.py_** works! But when I run **_test_image.py_** there comes another issue

**_SSIM weight ----- 1e2
Model DenseFuse_net : params: 0.296772M
Traceback (most recent call last):
  File "test_image.py", line 124, in <module>
    main()
  File "test_image.py", line 120, in main
    run_demo(model, infrared_path, visible_path, output_path, index, fusion_type, network_type, strategy_type, ssim_weight_str, mode)
  File "test_image.py", line 68, in run_demo
    img = img_fusion.cpu().clamp(0, 255).data[0].numpy()
AttributeError: 'list' object has no attribute 'cpu'_**

I have already unpack the IV_images.zip & test_RGB.zip, and the path in **_args_fusion.py_** has been modified as 
**_model_path_gray = "./models/1e2/Final_epoch_4_Sat_Feb_29_14_02_48_2020_1e2.model"_**
Have I done something wrong when test the net or there still have some bug in this project?

**Comment by hli1221** [comment]
@lordbutters 
Thank you very much for your feedback. I have modified the codes in 'test_img.py'.
Please update your project.

**Comment by lordbutters** [comment]
> @lordbutters
> Thank you very much for your feedback. I have modified the codes in 'test_img.py'.
> Please update your project.

Here is the new error report when I run **_test_image.py_**

**_SSIM weight ----- 1e2
Model DenseFuse_net : params: 0.296772M
Traceback (most recent call last):
  File "test_image.py", line 124, in <module>
    main()
  File "test_image.py", line 120, in main
    run_demo(model, infrared_path, visible_path, output_path, index, fusion_type, network_type, strategy_type, ssim_weight_str, mode)
  File "test_image.py", line 72, in run_demo
    utils.save_images(output_path, img)
  File "/home/maiyuki/Documents/densefuse-pytorch-master/utils.py", line 168, in save_images
    imsave(path, data)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 199, in imsave
    im.save(name)
  File "/home/maiyuki/anaconda2/envs/densefuse/lib/python3.6/site-packages/PIL/Image.py", line 2004, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './outputs/fusion_auto_1_network_densefuse_addition_1e2.png'_**

**Comment by hli1221** [comment]
@lordbutters 
You should  create a folder named 'outputs' in root path of your project.

**Comment by lordbutters** [comment]
> @lordbutters
> You should create a folder named 'outputs' in root path of your project.

ok, it works! Thank you!
